version: "3.8"

services:
  db:
    image: postgres:15
    container_name: tcc-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"        # <<--- mapeamento desejado: host:1643 -> container:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rafarod
      POSTGRES_DB: turnstile_system
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d turnstile_system -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
